name: Example workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    print_file:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: ls .

